package net.nosocial.traits.gui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class AboutForm {
    private JTextPane pFontFamilySansTextPane;
    private JPanel panel1;
    private JButton OKButton;

    public AboutForm() {
        OKButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFrame frame = (JFrame) SwingUtilities.getRoot(OKButton);
                frame.dispose();
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("NSN Traits v2.0 — About");
        frame.setContentPane(new AboutForm().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null); // center
        frame.setVisible(true);
    }

    public static void displayDialog() {
        JFrame frame = new JFrame("NSN Traits v2.0 — About");
        frame.setContentPane(new AboutForm().panel1);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null); // center
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:m:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.setEnabled(true);
        pFontFamilySansTextPane = new JTextPane();
        pFontFamilySansTextPane.setContentType("text/html");
        pFontFamilySansTextPane.setEditable(false);
        pFontFamilySansTextPane.setEnabled(true);
        pFontFamilySansTextPane.setMargin(new Insets(40, 40, 40, 40));
        pFontFamilySansTextPane.setOpaque(false);
        pFontFamilySansTextPane.setText("<html>\n  <head>\n    <style type=\"text/css\">\n      <!--\n        p { font-family: sans-serif; font-size: 16pt }\n        p,li { font-family: sans-serif; font-size: 16pt }\n        li { font-family: sans-serif; font-size: 16pt }\n      -->\n    </style>\n    \n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      Welcome to <b>NSN Traits v2.0</b> &#8212; your daily assistant in learning a \n      personality!\n    </p>\n    <p>\n      Answer as many questions as possible to get the personal profile of \n      positive and negative traits.\n    </p>\n    <ul>\n      <li>\n        <p>\n          <b>Self awareness</b><br>Learn about behaviors, discover your traits \n          and develop emotional intelligence\n        </p>\n      </li>\n      <li>\n        <p>\n          <b>Dealing with people</b><br>The more self-aware you are, the more \n          skilled you are at reading personality of others\n        </p>\n      </li>\n      <li>\n        <p>\n          <b>A key to life success</b><br>Use NSN Traits v2.0 day by day and \n          watch how your life becomes easier and more successful\n        </p>\n      </li>\n    </ul>\n    <p style=\"margin-top: 0\">\n      Copyright &#169; NSN 2015-2022.\n    </p>\n    <p>\n      For help and support contact <a href=\"mailto:traits@nosocial.net\">traits@nosocial.net</a>.\n    </p>\n  </body>\n</html>\n");
        CellConstraints cc = new CellConstraints();
        panel1.add(pFontFamilySansTextPane, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.TOP));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:max(d;4px):grow,left:4dlu:noGrow,fill:d:noGrow,left:3dlu:noGrow,fill:max(d;4px):grow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.add(panel2, cc.xy(1, 3));
        OKButton = new JButton();
        OKButton.setText("OK");
        panel2.add(OKButton, cc.xy(3, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
